server:
  port: 10086
eureka:
  client:
    register-with-eureka: false # eureka 注销注册
    fetch-registry: false # 禁止拉取服务
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: ly-registry